import type { Ability, CardDef } from '@fftcg/engine'

/**
 * The hand-written ability ASTs for the five rung-C1 clauses (spec C1-1/C1-10).
 *
 * WHY THIS FILE AND NOT `data/cards.json`: that file is FETCHED and regenerated by
 * `scripts/fetch-cards.ts`, so anything hand-written in it is wiped by the next `pnpm --filter
 * @fftcg/cards fetch`. The ASTs therefore live here, in source, and `loadCards()` merges them onto the
 * fetched defs. `data/cards.json` stays purely machine-owned; `def.text` in it stays the printed wording
 * that each `Ability.text` below is quoted from and that reviewers check the AST against.
 *
 * Every value here is a plain readonly record/array/string/number — no functions, `Map` or `Set` — because
 * these ride on `CardDef`, and `CardDef` rides through `viewFor`/`determinise`'s `structuredClone` and
 * `session.ts`'s serialisation (see the header of the engine's `abilities.ts`).
 */

// ---------------------------------------------------------------------------
// Per-clause coverage (spec C1-9)
// ---------------------------------------------------------------------------

/**
 * How many separate ability clauses each card PRINTS, whether or not any are implemented. Without this the
 * engine falls back to `hasAbilities ? 1 : 0`, and a card with 1 of its 2 clauses implemented would report
 * nothing missing — exactly the dishonest log C1-9 forbids.
 *
 * A clause is one ability, not one printed line: Shantotto and Ramuh each print their modes on their own
 * lines but are a single modal clause, so they count 1. Cards whose two clauses are a static/continuous
 * one plus an activated one (Odin, Sphene) count both.
 */
export const ABILITY_CLAUSES: Record<string, number> = {
  '1-121C': 1,    // [Lightning][Dull]: grant Haste
  '9-074C': 1,    // static: may produce Lightning CP
  '12-120C': 1,   // ETB, modal — the two quoted actions are one clause
  '13-072R': 2,   // static cost reduction | EX BURST break
  '16-092C': 2,   // ETB dull up to 2 | [Dull], self-break: dull all
  '18-064C': 1,   // [Earth], discard: draw 1
  '18-069C': 1,   // [Lightning], discard: draw 1
  '18-124C': 1,   // ETB return a Forward from the Break Zone
  '19-052C': 2,   // self-break: +4000 | remove from game: +2000
  '20-074C': 2,   // ETB reveal 5 | [2][Dull], self-break: draw 1
  '20-103H': 1,   // Summon, modal — the three quoted actions are one clause
  '20-105C': 1,   // EX BURST ETB look at top 3
  '22-068R': 2,   // when chosen: +2000 | on damaging the opponent: Break Zone retrieval
  '24-063H': 2,   // ETB search | when a cost-1 Forward enters your field
  '27-124S': 2,   // ETB mass pump | at the beginning of the Attack Phase
  '27-125S': 2,   // on damaging a Forward: break it | on damaging the opponent: modal
  '27-126S': 2,   // static Break Zone protection | [0]: retrieve
  '27-127S': 2,   // EX BURST ETB break | when an opponent's Forward is broken
}

// ---------------------------------------------------------------------------
// The five implemented clauses (spec C1-10)
// ---------------------------------------------------------------------------

/**
 * Noel's ETB only. The `EX BURST` tag is quoted in `text` because that is the printed wording, but EX Burst
 * itself is rung C3: this clause fires on a NORMAL cast, which is what `enterField` means. Noel's second
 * clause (the [Dull] action ability) is C3 and keeps warning — hence `ABILITY_CLAUSES['16-092C'] === 2`.
 *
 * `min: 0` is "up to 2": declining is a legal answer, and the engine still raises the choice.
 */
const NOEL_ETB: Ability = {
  id: '16-092C:etb',
  trigger: { kind: 'enterField' },
  text: 'EX BURST When Noel enters the field, choose up to 2 Forwards opponent controls. Dull them.',
  effects: [{
    kind: 'chooseTargets', min: 0, max: 2,
    from: { zone: 'forwards', controller: 'opponent' },
    then: [{ kind: 'dull' }],
  }],
}

/**
 * Shantotto's ETB: a mode choice whose chosen branch then raises a target choice — two `apply` calls, and
 * the reason the agenda has a program counter at all (spec C1-3).
 *
 * Mode 1 is "other than Shantotto" (`excludeSource`) over EITHER player's Forwards — the printed text
 * restricts the identity, not the controller. Mode 2 is "you control" (`controller: 'self'`) with no
 * exclusion, so Shantotto may protect itself. `cannotBeBroken` is a flag, not a keyword: `granted` holds
 * only real Keywords (spec C1-7).
 */
const SHANTOTTO_ETB: Ability = {
  id: '12-120C:etb',
  trigger: { kind: 'enterField' },
  text: 'When Shantotto enters the field, select 1 of the 2 following actions.\n'
    + '"Choose 1 Forward other than Shantotto. It gains Haste until the end of the turn."\n'
    + '"Choose 1 Forward you control. It gains ‘This Forward cannot be broken’ until the end of the turn."',
  effects: [{
    kind: 'chooseModes', min: 1, max: 1,
    modes: [
      {
        label: 'Choose 1 Forward other than Shantotto. It gains Haste until the end of the turn.',
        effects: [{
          kind: 'chooseTargets', min: 1, max: 1,
          from: { zone: 'forwards', controller: 'any', filter: { excludeSource: true } },
          then: [{ kind: 'grantKeyword', keyword: 'haste' }],
        }],
      },
      {
        label: 'Choose 1 Forward you control. It gains ‘This Forward cannot be broken’ until the end of the turn.',
        effects: [{
          kind: 'chooseTargets', min: 1, max: 1,
          from: { zone: 'forwards', controller: 'self' },
          then: [{ kind: 'grantFlag', flag: 'cannotBeBroken' }],
        }],
      },
    ],
  }],
}

/**
 * Cloud's ETB only. Untargeted and unconditional, so it raises no prompt: `forEach` binds each of your
 * Forwards in turn. Cloud is already on the field when its own ETB resolves, so it pumps itself too —
 * that is the printed effect ("all the Forwards you control"), not an oversight.
 *
 * Cloud's second clause (at the beginning of the Attack Phase) needs a phase continuation and is C2; it
 * keeps warning.
 */
const CLOUD_ETB: Ability = {
  id: '27-124S:etb',
  trigger: { kind: 'enterField' },
  text: 'When Cloud enters the field, until the end of the turn, all the Forwards you control gain 3000 power and Brave.',
  effects: [{
    kind: 'forEach',
    from: { zone: 'forwards', controller: 'self' },
    do: [{ kind: 'addPower', amount: 3000 }, { kind: 'grantKeyword', keyword: 'brave' }],
  }],
}

/**
 * Billy Bob's ETB — the only Break-Zone-targeting clause in C1. "other than Card Name Billy Bob" excludes
 * every card sharing the source's NAME (`excludeSourceName`), not just this instance: a second Billy Bob in
 * the Break Zone is an illegal target too. The Break Zone holds Backups and Summons as well, hence the
 * explicit `type: 'forward'` filter — `zone: 'breakZone'` alone does not imply one.
 *
 * `min: 1` with an empty Break Zone is a logged no-op, not an error (spec C1-7).
 */
const BILLY_BOB_ETB: Ability = {
  id: '18-124C:etb',
  trigger: { kind: 'enterField' },
  text: 'When Billy Bob enters the field, choose 1 Forward other than Card Name Billy Bob in your Break Zone. Add it to your hand.',
  effects: [{
    kind: 'chooseTargets', min: 1, max: 1,
    from: { zone: 'breakZone', controller: 'self', filter: { type: 'forward', excludeSourceName: true } },
    then: [{ kind: 'moveToHand' }],
  }],
}

/**
 * Ramuh — the only `summonResolve` clause in the pool, and therefore the only exercise of the Summon
 * resolution path. `min: 0` is "up to 2": selecting nothing is legal. Chosen modes resolve in PRINTED
 * order regardless of the order they were picked in (the engine sorts the answer), each raising its own
 * target choice in turn, so a two-mode answer costs three `apply` calls in total.
 *
 * "Choose 1 Forward" is unrestricted, so `controller: 'any'` — Ramuh can dull or burn your own Forward,
 * and granting Haste to one of yours is the point of mode 3.
 *
 * By the time these resolve Ramuh is already in the Break Zone (no stack, §7.10.1 / spec C1-4);
 * `Frame.source` is allowed to be a card that is not on the field.
 */
const RAMUH_SUMMON: Ability = {
  id: '20-103H:summon',
  trigger: { kind: 'summonResolve' },
  text: 'Select up to 2 of the 3 following actions.\n'
    + '"Choose 1 Forward. Dull it."\n'
    + '"Choose 1 Forward. Deal it 5000 damage."\n'
    + '"Choose 1 Forward. It gains Haste until the end of the turn."',
  effects: [{
    kind: 'chooseModes', min: 0, max: 2,
    modes: [
      {
        label: 'Choose 1 Forward. Dull it.',
        effects: [{ kind: 'chooseTargets', min: 1, max: 1, from: { zone: 'forwards', controller: 'any' }, then: [{ kind: 'dull' }] }],
      },
      {
        label: 'Choose 1 Forward. Deal it 5000 damage.',
        effects: [{ kind: 'chooseTargets', min: 1, max: 1, from: { zone: 'forwards', controller: 'any' }, then: [{ kind: 'damage', amount: 5000 }] }],
      },
      {
        label: 'Choose 1 Forward. It gains Haste until the end of the turn.',
        effects: [{ kind: 'chooseTargets', min: 1, max: 1, from: { zone: 'forwards', controller: 'any' }, then: [{ kind: 'grantKeyword', keyword: 'haste' }] }],
      },
    ],
  }],
}

/** Implemented clauses by card code. A card absent from here has none — every clause it prints still warns. */
export const ABILITIES: Record<string, readonly Ability[]> = {
  '12-120C': [SHANTOTTO_ETB],
  '16-092C': [NOEL_ETB],
  '18-124C': [BILLY_BOB_ETB],
  '20-103H': [RAMUH_SUMMON],
  '27-124S': [CLOUD_ETB],
}

/**
 * Merge the hand-written ASTs and clause counts onto fetched defs. Pure and free of `node:fs`, so the web
 * app — which imports `data/cards.json` directly because the package index reads the file with `node:fs`
 * (see `apps/web/src/deck.ts`) — can call this and play the SAME ability game the CLI does.
 */
export function withAbilities(defs: readonly CardDef[]): CardDef[] {
  return defs.map((def) => {
    const abilities = ABILITIES[def.code]
    const clauses = ABILITY_CLAUSES[def.code]
    return {
      ...def,
      ...(abilities ? { abilities } : {}),
      ...(clauses === undefined ? {} : { abilityClauses: clauses }),
    }
  })
}
