import type { Ability, CardDef, CardType } from '@fftcg/engine'

/**
 * The hand-written ability ASTs: the five rung-C1 clauses (spec C1-1/C1-10) plus C2's five (C2-12).
 *
 * WHY THIS FILE AND NOT `data/cards.json`: that file is FETCHED and regenerated by
 * `scripts/fetch-cards.ts`, so anything hand-written in it is wiped by the next `pnpm --filter
 * @fftcg/cards fetch`. The ASTs therefore live here, in source, and `loadCards()` merges them onto the
 * fetched defs. `data/cards.json` stays purely machine-owned; `def.text` in it stays the printed wording
 * that each `Ability.text` below is quoted from and that reviewers check the AST against.
 *
 * Every value here is a plain readonly record/array/string/number — no functions, `Map` or `Set` — because
 * these ride on `CardDef`, and `CardDef` rides through `viewFor`/`determinise`'s `structuredClone` and
 * `session.ts`'s serialisation (see the header of the engine's `abilities.ts`).
 */

// ---------------------------------------------------------------------------
// Per-clause coverage (spec C1-9)
// ---------------------------------------------------------------------------

/**
 * How many separate ability clauses each card PRINTS, whether or not any are implemented. Without this the
 * engine falls back to `hasAbilities ? 1 : 0`, and a card with 1 of its 2 clauses implemented would report
 * nothing missing — exactly the dishonest log C1-9 forbids.
 *
 * A clause is one ability, not one printed line: Shantotto and Ramuh each print their modes on their own
 * lines but are a single modal clause, so they count 1. Cards whose two clauses are a static/continuous
 * one plus an activated one (Odin, Sphene) count both.
 */
export const ABILITY_CLAUSES: Record<string, number> = {
  '1-121C': 1,    // [Lightning][Dull]: grant Haste
  '9-074C': 1,    // static: may produce Lightning CP
  '12-120C': 1,   // ETB, modal — the two quoted actions are one clause
  '13-072R': 2,   // static cost reduction | EX BURST break
  '16-092C': 2,   // ETB dull up to 2 | [Dull], self-break: dull all
  '18-064C': 1,   // [Earth], discard: draw 1
  '18-069C': 1,   // [Lightning], discard: draw 1
  '18-124C': 1,   // ETB return a Forward from the Break Zone
  '19-052C': 2,   // self-break: +4000 | remove from game: +2000
  '20-074C': 2,   // ETB reveal 5 | [2][Dull], self-break: draw 1
  '20-103H': 1,   // Summon, modal — the three quoted actions are one clause
  '20-105C': 1,   // EX BURST ETB look at top 3
  '22-068R': 2,   // when chosen: +2000 (deferred, spec C2-13) | on damaging the opponent: Break Zone retrieval
  '24-063H': 2,   // ETB search | when a cost-1 Forward enters your field
  '27-124S': 2,   // ETB mass pump | at the beginning of the Attack Phase
  '27-125S': 2,   // on damaging a Forward: break it | on damaging the opponent: modal — both C2, so 0 warnings
  '27-126S': 2,   // static Break Zone protection | [0]: retrieve
  '27-127S': 2,   // EX BURST ETB break | when an opponent's Forward is broken — both C2 stage 1, so 0 warnings
}

// ---------------------------------------------------------------------------
// The five implemented clauses (spec C1-10)
// ---------------------------------------------------------------------------

/**
 * Noel's ETB only. The `EX BURST` tag is quoted in `text` because that is the printed wording, but EX Burst
 * itself is rung C3: this clause fires on a NORMAL cast, which is what `enterField` means. Noel's second
 * clause (the [Dull] action ability) is C3 and keeps warning — hence `ABILITY_CLAUSES['16-092C'] === 2`.
 *
 * `min: 0` is "up to 2": declining is a legal answer, and the engine still raises the choice.
 */
const NOEL_ETB: Ability = {
  id: '16-092C:etb',
  trigger: { kind: 'enterField' },
  text: 'EX BURST When Noel enters the field, choose up to 2 Forwards opponent controls. Dull them.',
  effects: [{
    kind: 'chooseTargets', min: 0, max: 2,
    from: { zone: 'forwards', controller: 'opponent' },
    then: [{ kind: 'dull' }],
  }],
}

/**
 * Shantotto's ETB: a mode choice whose chosen branch then raises a target choice — two `apply` calls, and
 * the reason the agenda has a program counter at all (spec C1-3).
 *
 * Mode 1 is "other than Shantotto" (`excludeSource`) over EITHER player's Forwards — the printed text
 * restricts the identity, not the controller. Mode 2 is "you control" (`controller: 'self'`) with no
 * exclusion, so Shantotto may protect itself. `cannotBeBroken` is a flag, not a keyword: `granted` holds
 * only real Keywords (spec C1-7).
 */
const SHANTOTTO_ETB: Ability = {
  id: '12-120C:etb',
  trigger: { kind: 'enterField' },
  text: 'When Shantotto enters the field, select 1 of the 2 following actions.\n'
    + '"Choose 1 Forward other than Shantotto. It gains Haste until the end of the turn."\n'
    + '"Choose 1 Forward you control. It gains ‘This Forward cannot be broken’ until the end of the turn."',
  effects: [{
    kind: 'chooseModes', min: 1, max: 1,
    modes: [
      {
        label: 'Choose 1 Forward other than Shantotto. It gains Haste until the end of the turn.',
        effects: [{
          kind: 'chooseTargets', min: 1, max: 1,
          from: { zone: 'forwards', controller: 'any', filter: { excludeSource: true } },
          then: [{ kind: 'grantKeyword', keyword: 'haste' }],
        }],
      },
      {
        label: 'Choose 1 Forward you control. It gains ‘This Forward cannot be broken’ until the end of the turn.',
        effects: [{
          kind: 'chooseTargets', min: 1, max: 1,
          from: { zone: 'forwards', controller: 'self' },
          then: [{ kind: 'grantFlag', flag: 'cannotBeBroken' }],
        }],
      },
    ],
  }],
}

/**
 * Cloud's ETB only. Untargeted and unconditional, so it raises no prompt: `forEach` binds each of your
 * Forwards in turn. Cloud is already on the field when its own ETB resolves, so it pumps itself too —
 * that is the printed effect ("all the Forwards you control"), not an oversight.
 *
 * Cloud's second clause (at the beginning of the Attack Phase) needs a phase continuation and is C2; it
 * keeps warning.
 */
const CLOUD_ETB: Ability = {
  id: '27-124S:etb',
  trigger: { kind: 'enterField' },
  text: 'When Cloud enters the field, until the end of the turn, all the Forwards you control gain 3000 power and Brave.',
  effects: [{
    kind: 'forEach',
    from: { zone: 'forwards', controller: 'self' },
    do: [{ kind: 'addPower', amount: 3000 }, { kind: 'grantKeyword', keyword: 'brave' }],
  }],
}

/**
 * Billy Bob's ETB — the only Break-Zone-targeting clause in C1. "other than Card Name Billy Bob" excludes
 * every card sharing the source's NAME (`excludeSourceName`), not just this instance: a second Billy Bob in
 * the Break Zone is an illegal target too. The Break Zone holds Backups and Summons as well, hence the
 * explicit `type: 'forward'` filter — `zone: 'breakZone'` alone does not imply one.
 *
 * `min: 1` with an empty Break Zone is a logged no-op, not an error (spec C1-7).
 */
const BILLY_BOB_ETB: Ability = {
  id: '18-124C:etb',
  trigger: { kind: 'enterField' },
  text: 'When Billy Bob enters the field, choose 1 Forward other than Card Name Billy Bob in your Break Zone. Add it to your hand.',
  effects: [{
    kind: 'chooseTargets', min: 1, max: 1,
    from: { zone: 'breakZone', controller: 'self', filter: { type: 'forward', excludeSourceName: true } },
    then: [{ kind: 'moveToHand' }],
  }],
}

/**
 * Ramuh — the only `summonResolve` clause in the pool, and therefore the only exercise of the Summon
 * resolution path. `min: 0` is "up to 2": selecting nothing is legal. Chosen modes resolve in PRINTED
 * order regardless of the order they were picked in (the engine sorts the answer), each raising its own
 * target choice in turn, so a two-mode answer costs three `apply` calls in total.
 *
 * "Choose 1 Forward" is unrestricted, so `controller: 'any'` — Ramuh can dull or burn your own Forward,
 * and granting Haste to one of yours is the point of mode 3.
 *
 * By the time these resolve Ramuh is already in the Break Zone (no stack, §7.10.1 / spec C1-4);
 * `Frame.source` is allowed to be a card that is not on the field.
 */
const RAMUH_SUMMON: Ability = {
  id: '20-103H:summon',
  trigger: { kind: 'summonResolve' },
  text: 'Select up to 2 of the 3 following actions.\n'
    + '"Choose 1 Forward. Dull it."\n'
    + '"Choose 1 Forward. Deal it 5000 damage."\n'
    + '"Choose 1 Forward. It gains Haste until the end of the turn."',
  effects: [{
    kind: 'chooseModes', min: 0, max: 2,
    modes: [
      {
        label: 'Choose 1 Forward. Dull it.',
        effects: [{ kind: 'chooseTargets', min: 1, max: 1, from: { zone: 'forwards', controller: 'any' }, then: [{ kind: 'dull' }] }],
      },
      {
        label: 'Choose 1 Forward. Deal it 5000 damage.',
        effects: [{ kind: 'chooseTargets', min: 1, max: 1, from: { zone: 'forwards', controller: 'any' }, then: [{ kind: 'damage', amount: 5000 }] }],
      },
      {
        label: 'Choose 1 Forward. It gains Haste until the end of the turn.',
        effects: [{ kind: 'chooseTargets', min: 1, max: 1, from: { zone: 'forwards', controller: 'any' }, then: [{ kind: 'grantKeyword', keyword: 'haste' }] }],
      },
    ],
  }],
}

// ---------------------------------------------------------------------------
// The rung-C2 stage-1 clauses (spec C2-12)
// ---------------------------------------------------------------------------

/**
 * Lightning's ETB. As with Noel, the `EX BURST` tag is quoted because it is printed, but EX Burst is a separate
 * mechanic (C4) governing what happens when this card is taken as damage — the trigger below fires on a NORMAL
 * cast, which is what `enterField` means. Lightning's two printed clauses are both implemented here, so it stops
 * warning entirely (spec C2-A10).
 *
 * "of cost 4 or less" is `maxCost: 4` against the PRINTED cost; "opponent controls" is the target's controller.
 */
const LIGHTNING_ETB: Ability = {
  id: '27-127S:etb',
  trigger: { kind: 'enterField' },
  text: 'EX BURST When Lightning enters the field, choose 1 Forward of cost 4 or less opponent controls. Break it.',
  effects: [{
    kind: 'chooseTargets', min: 1, max: 1,
    from: { zone: 'forwards', controller: 'opponent', filter: { maxCost: 4 } },
    then: [{ kind: 'breakCard' }],
  }],
}

/**
 * The rung's first OBSERVER trigger: the clause belongs to Lightning, but the event happens to a DIFFERENT card
 * (spec C2-3/C2-4). `whose: 'opponent'` is relative to Lightning's own controller, never the turn player, so the
 * clause means the same thing from either seat (spec C2-10).
 *
 * CR §11.8.6: two opponent Forwards broken at the same instant are two separate occurrences and this triggers
 * twice — the engine collects one occurrence per (watcher, clause, transition), not one per batch.
 */
const LIGHTNING_OPPONENT_BROKEN: Ability = {
  id: '27-127S:opponent-forward-broken',
  trigger: { kind: 'observesZoneChange', from: 'field', to: 'breakZone', whose: 'opponent', of: 'forward' },
  text: 'When a Forward opponent controls is put from the field into the Break Zone, choose 1 Forward you control. It gains Haste until the end of the turn.',
  effects: [{
    kind: 'chooseTargets', min: 1, max: 1,
    from: { zone: 'forwards', controller: 'self' },
    then: [{ kind: 'grantKeyword', keyword: 'haste' }],
  }],
}

/**
 * "Character" is Forward, Backup or Monster and never Summon (§7.2). A single `TargetFilter.type` cannot say that,
 * which is why `types` exists (spec C2-9); both Break-Zone retrievals below are worded "1 Character".
 */
const CHARACTER: readonly CardType[] = ['forward', 'backup', 'monster']

/**
 * Luso's damage trigger, and the reason `Frame.triggerEvent` and `onSubject` exist (spec C2-5). "Break **it**"
 * names the Forward Luso just damaged: it is NOT a `chooseTargets` over one candidate, because offering it as a
 * choice would let the player decline or retarget a printed effect. `onSubject` binds the trigger event's
 * subject and runs `breakCard` on it.
 *
 * Combat damage and ability damage both fire this — the text says "deals damage", not "deals combat damage"
 * (spec C2-7). On LETHAL damage §12.4.5 has already broken the Forward by the time this resolves (spec C2-6),
 * so the `breakCard` is a silent no-op and the card is in the Break Zone either way.
 *
 * Luso's second clause is `LUSO_DAMAGES_OPPONENT` below, so Luso warns about nothing at all (spec C2-A10).
 */
const LUSO_DAMAGES_FORWARD: Ability = {
  id: '27-125S:damages-forward',
  trigger: { kind: 'dealtDamage', to: 'forward', whose: 'any' },
  text: 'When Luso deals damage to a Forward, break it.',
  effects: [{ kind: 'onSubject', do: [{ kind: 'breakCard' }] }],
}

// ---------------------------------------------------------------------------
// The rung-C2 stage-2 clauses (spec C2-12)
// ---------------------------------------------------------------------------

/**
 * Luso's second clause — the hardest in the rung, because four things meet in it: a `dealtDamage` trigger on the
 * PLAYER (which only fires reliably because party attribution is by membership, spec C2-8), a 0..2 modal choice,
 * "1 Character" needing `types` (spec C2-9), and a mode that CASCADES into Luso's own first clause — the 3000
 * damage makes Luso a damage source again, so `27-125S:damages-forward` queues behind this frame and breaks
 * whatever §12.4.5 left standing. The cascade terminates: the damaged Forward leaves the field either way.
 *
 * "select up to 2 of the 2 following actions" is `min: 0, max: 2` — taking neither is a legal answer — and both
 * chosen modes resolve in PRINTED order regardless of the order they were named (the engine sorts the answer).
 * "Choose 1 Forward" is unrestricted, so `controller: 'any'`: Luso may burn one of its own side.
 */
const LUSO_DAMAGES_OPPONENT: Ability = {
  id: '27-125S:damages-opponent',
  trigger: { kind: 'dealtDamage', to: 'player', whose: 'opponent' },
  text: 'When Luso deals damage to your opponent, select up to 2 of the 2 following actions. '
    + '"Choose 1 Forward. Deal it 3000 damage." "Choose 1 Character in your Break Zone. Add it to your hand."',
  effects: [{
    kind: 'chooseModes', min: 0, max: 2,
    modes: [
      {
        label: 'Choose 1 Forward. Deal it 3000 damage.',
        effects: [{ kind: 'chooseTargets', min: 1, max: 1, from: { zone: 'forwards', controller: 'any' }, then: [{ kind: 'damage', amount: 3000 }] }],
      },
      {
        label: 'Choose 1 Character in your Break Zone. Add it to your hand.',
        effects: [{ kind: 'chooseTargets', min: 1, max: 1, from: { zone: 'breakZone', controller: 'self', filter: { types: CHARACTER } }, then: [{ kind: 'moveToHand' }] }],
      },
    ],
  }],
}

/**
 * Prishe's second clause: the same player-damage trigger and the same "1 Character" retrieval as Luso's mode 2,
 * without the modal wrapper. `min: 1` over a Break Zone holding no Character is a logged no-op (spec C1-7).
 *
 * Prishe's FIRST clause ("When Prishe is chosen by a Summon or an ability, …") is deliberately out of scope
 * (spec C2-13): it would have to fire while a frame is already mid-flight choosing its targets, and the agenda
 * cannot preempt an active frame — the one thing spec C2-A9 pins that it must never do. It keeps warning.
 */
const PRISHE_DAMAGES_OPPONENT: Ability = {
  id: '22-068R:damages-opponent',
  trigger: { kind: 'dealtDamage', to: 'player', whose: 'opponent' },
  text: 'When Prishe deals damage to your opponent, choose 1 Character in your Break Zone. Add it to your hand.',
  effects: [{
    kind: 'chooseTargets', min: 1, max: 1,
    from: { zone: 'breakZone', controller: 'self', filter: { types: CHARACTER } },
    then: [{ kind: 'moveToHand' }],
  }],
}

/**
 * Odin's Summon effect (spec C4). Structurally Lightning's ETB — a `maxCost` target then `breakCard` — with
 * two differences worth reading off the printed text rather than assuming:
 *
 * - "Choose 1 Forward", not "a Forward opponent controls", so `controller: 'any'`. Breaking your own Forward
 *   is legal and almost always bad, which is the card's business, not the engine's.
 * - `maxCost: 5` is the PRINTED cost of the target. Odin's own first clause reduces the cost to CAST Odin;
 *   neither that nor any other modifier is meant to move a target's printed cost, and `targetCandidates`
 *   reads `def.cost` for exactly that reason.
 *
 * The `EX BURST` tag is quoted because it is printed, but EX Burst itself is not implemented: this clause
 * fires on a NORMAL cast, which is what `summonResolve` means. That is the same treatment C1 gave Noel and
 * Lightning, and `ABILITY_CLAUSES['13-072R']` stays at 2 so the card keeps warning about the clause it is
 * still missing.
 */
const ODIN_SUMMON: Ability = {
  id: '13-072R:summon',
  trigger: { kind: 'summonResolve' },
  text: 'EX BURST Choose 1 Forward of cost 5 or less. Break it.',
  effects: [{
    kind: 'chooseTargets', min: 1, max: 1,
    from: { zone: 'forwards', controller: 'any', filter: { maxCost: 5 } },
    then: [{ kind: 'breakCard' }],
  }],
}

// ---------------------------------------------------------------------------
// Activated abilities (spec C3)
// ---------------------------------------------------------------------------

/**
 * The first abilities in this pool a PLAYER chooses to use rather than merely receives. `trigger.kind` is
 * `'activated'` — not a trigger at all, but it lives in that union so trigger dispatch inertly ignores it and
 * the compiler still checks every switch.
 *
 * Two things about the costs are easy to get wrong and are load-bearing here:
 *
 * - The CP cost is NOT the card's printed cost. Red Mage 1-121C costs 2 to cast and its ability costs
 *   `[Lightning]` — one CP, Lightning. Miner costs 3 to cast and its ability costs a generic `[2]`.
 * - `dull: true` is what brings the "must be active, and not the turn it entered unless it has Haste" rule
 *   (§11.6.2.2). Undead Princess has no dull icon, so she may be used while dulled and on the turn she
 *   arrives — she is the fixture that keeps that gate honest.
 */
const RED_MAGE_HASTE: Ability = {
  id: '1-121C:haste',
  trigger: {
    kind: 'activated', sourceZone: 'field',
    // The source may not dull ITSELF to make this Lightning CP — that one dull would otherwise pay both the
    // CP and the [Dull]. `generateCp` excludes it (spec C3-5).
    cost: { cp: { amount: 1, requiredElements: ['lightning'] }, dull: true },
  },
  text: '[Lightning][Dull]: Choose 1 Forward. It gains Haste until the end of the turn.',
  effects: [{
    kind: 'chooseTargets', min: 1, max: 1,
    // "Choose 1 Forward" — either player's, unrestricted. Granting the OPPONENT Haste is legal and useless,
    // which is the printed text's business, not the engine's.
    from: { zone: 'forwards', controller: 'any' },
    then: [{ kind: 'grantKeyword', keyword: 'haste' }],
  }],
}

/**
 * Noel's action. Its cost dulls AND removes its own source, so by the time "dull all the Forwards opponent
 * controls" resolves, Noel is in the Break Zone — the effect must still resolve in full (spec C3-A2).
 * `forEach` is untargeted: "all" is not a choice.
 */
const NOEL_DULL_ALL: Ability = {
  id: '16-092C:dull-all',
  trigger: { kind: 'activated', sourceZone: 'field', cost: { dull: true, selfToBreakZone: true } },
  text: '[Dull], put Noel into the Break Zone: Dull all the Forwards opponent controls.',
  effects: [{ kind: 'forEach', from: { zone: 'forwards', controller: 'opponent' }, do: [{ kind: 'dull' }] }],
}

/**
 * Miner's action. Miner's OTHER printed clause — the ETB deck reveal — is rung C6, so this is the card's
 * second printed clause arriving first. That is exactly why commands carry `abilityId` and not an index into
 * this array (spec C3-2): an index would silently shift when the ETB lands.
 */
const MINER_DRAW: Ability = {
  id: '20-074C:draw',
  trigger: { kind: 'activated', sourceZone: 'field', cost: { cp: { amount: 2 }, dull: true, selfToBreakZone: true } },
  text: '[2][Dull], put Miner into the Break Zone: Draw 1 card.',
  effects: [{ kind: 'draw', count: 1 }],
}

/**
 * Undead Princess's first clause. No dull icon and no CP: the entire cost is putting herself into the Break
 * Zone, which makes her the fixture for two rules at once — that the `[Dull]` restrictions do NOT apply
 * without the icon, and that a target preflight runs against the POST-cost state. She has already left the
 * field when targets are computed, so she cannot pump herself, and if she is the only Forward the activation
 * is illegal rather than a cost paid for nothing (§11.6.5).
 */
const UNDEAD_PRINCESS_PUMP: Ability = {
  id: '19-052C:pump',
  trigger: { kind: 'activated', sourceZone: 'field', cost: { selfToBreakZone: true } },
  text: 'Put Undead Princess into the Break Zone: Choose 1 Forward. It gains +4000 power until the end of the turn.',
  effects: [{
    kind: 'chooseTargets', min: 1, max: 1,
    from: { zone: 'forwards', controller: 'any' },
    then: [{ kind: 'addPower', amount: 4000 }],
  }],
}

/**
 * The two hand-sourced draws. `sourceZone: 'hand'` is what encodes "You can only use this ability if <card>
 * is in your hand" — an activation precondition, not a cost (spec C3-3). They are otherwise identical, and
 * they exist in this rung to prove the source zone is real rather than assumed to be the field.
 */
const GEOMANCER_DRAW: Ability = {
  id: '18-064C:draw',
  trigger: {
    kind: 'activated', sourceZone: 'hand',
    cost: { cp: { amount: 1, requiredElements: ['earth'] }, selfDiscard: true },
  },
  text: '[Earth], discard Geomancer: Draw 1 card. You can only use this ability if Geomancer is in your hand.',
  effects: [{ kind: 'draw', count: 1 }],
}

const RED_MAGE_18_DRAW: Ability = {
  id: '18-069C:draw',
  trigger: {
    kind: 'activated', sourceZone: 'hand',
    cost: { cp: { amount: 1, requiredElements: ['lightning'] }, selfDiscard: true },
  },
  text: '[Lightning], discard Red Mage: Draw 1 card. You can only use this ability if Red Mage is in your hand.',
  effects: [{ kind: 'draw', count: 1 }],
}

/** Implemented clauses by card code. A card absent from here has none — every clause it prints still warns. */
export const ABILITIES: Record<string, readonly Ability[]> = {
  '1-121C': [RED_MAGE_HASTE],
  '12-120C': [SHANTOTTO_ETB],
  // The Summon effect only; the conditional cost reduction is the other printed clause.
  '13-072R': [ODIN_SUMMON],
  // Printed order: the ETB is clause 1, the action clause 2.
  '16-092C': [NOEL_ETB, NOEL_DULL_ALL],
  '18-064C': [GEOMANCER_DRAW],
  '18-069C': [RED_MAGE_18_DRAW],
  '18-124C': [BILLY_BOB_ETB],
  // Clause 1 only; the "remove from the Break Zone from the game" clause is C4.
  '19-052C': [UNDEAD_PRINCESS_PUMP],
  // The card's SECOND printed clause, landing first — its ETB deck reveal is C6.
  '20-074C': [MINER_DRAW],
  '20-103H': [RAMUH_SUMMON],
  '22-068R': [PRISHE_DAMAGES_OPPONENT],
  '27-124S': [CLOUD_ETB],
  '27-125S': [LUSO_DAMAGES_FORWARD, LUSO_DAMAGES_OPPONENT],
  '27-127S': [LIGHTNING_ETB, LIGHTNING_OPPONENT_BROKEN],
}

/**
 * Merge the hand-written ASTs and clause counts onto fetched defs. Pure and free of `node:fs`, so the web
 * app — which imports `data/cards.json` directly because the package index reads the file with `node:fs`
 * (see `apps/web/src/deck.ts`) — can call this and play the SAME ability game the CLI does.
 */
export function withAbilities(defs: readonly CardDef[]): CardDef[] {
  return defs.map((def) => {
    const abilities = ABILITIES[def.code]
    const clauses = ABILITY_CLAUSES[def.code]
    return {
      ...def,
      ...(abilities ? { abilities } : {}),
      ...(clauses === undefined ? {} : { abilityClauses: clauses }),
    }
  })
}
